import React from 'react';
import Head from 'next/head';
import Newsletter from '../components/sections/Newsletter';
import Roadmap from '../components/sections/Roadmap';
import Faqs from '../components/sections/Faqs';

export default function About() {
    return (
        <React.Fragment>
            <Head>
                <title>About - Fathom Yacht Club</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <main className="sm:pt-20">
                <section className="bg-background-light pt-20 sm:mt-1 pb-28">
                    <div className="container w-4/5">
                        <h1 className="text-primary text-center font-bold font-muli text-5xl sm:text-6xl py-4 mb-8">About Fathom Yacht Club</h1>
                        <p className="font-normal text-xl leading-9 mb-6">Fathom Yacht Club was created to be the worlds first tokenized membership to a social yacht club organization with dedicated access to real world yachts.  Membership in the club will provide access to members only events, various forms of virtual spaces including the metaverse and access to real world yachts throughout the world.</p>
                        <p className="font-normal text-xl leading-9 mb-4">Fathom Yacht Club is designed to be a bespoke experience for its members regardless of where the live.  Daily participation will be available through virtual platforms and our plan is to host events in various locations seasonally and there will be access to use yachts in the worlds best yachting destinations.</p>
                    </div>
                </section>

                <section className="about-membership-section pt-28 pb-28">
                    <div className="container w-4/5">
                        <div className="max-w-2xl shadow-md bg-gradient-to-br from-green-overlay to-background-secondary bg-white text-copy-dark mx-auto py-12 px-8">
                            <h3 className="font-muli text-3xl sm:text-5xl text-copy-dark font-light mb-4">Membership Allocation</h3>

                            <div className="mb-4">
                                <h4 className="text-xxl font-medium mb-2">Presale: 250 Tokens</h4>
                                <h5 className="text-xl font-medium mb-2">100 Power, 100 Yacht & 50 Prestige</h5>
                                <p className="mb-2 font-light">Private sale March 2022</p>
                            </div>

                            <div className="mb-4">
                                <h4 className="text-xxl font-medium mb-2">Public launch: 2750 Tokens</h4>
                                <h5 className="text-xl font-medium mb-2">900 Power, 900 Yacht & 950 Prestige</h5>
                                <p className="mb-2 font-light">Public launch Spring 2022</p>
                            </div>
                            <div className="mb-0">
                                <h4 className="text-xxl font-medium mb-2">Reserves: 6000 Tokens</h4>
                                <p className="mb-2 font-light">Held back to ownership to further build the brand, engage the NFT community, create partnerships and collaborations, or sell/gift to ensure the project is sustainable and scalable</p>
                            </div>
                        </div>
                    </div>
                </section>

                <section className="container py-24">
                    <Roadmap />
                </section>

                <section className="py-8">
                    <Faqs />
                </section>
        
                <section>
                    <Newsletter />
                </section>
            </main>
        </React.Fragment>
    );
};