import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Collection from '../components/sections/Collection';
import { useSelector } from 'react-redux';
import Web3 from 'web3';

const { abi } = require("../contracts/FathomyachtClub.json");
const contractAddress = '0xd076900D9c5537d5F8886162Aba8900F506fD768';

export default function Location() {
    const [myTokens, setMyTokens] = useState([]);
    const [loading, setLoading] = useState(false);
    const walletAddr = useSelector((state) => state.address);
    // const router = useRouter();

    const getTokens = async () => {
        try {
            setLoading(true);
            const { ethereum } = window;
            var w3 = new Web3(ethereum);
            var contract_abi = new w3.eth.Contract(abi, w3.utils.toChecksumAddress(contractAddress));
            const tokens = await contract_abi.methods.getTokensOfHolder(walletAddr).call();
            console.log('[tokens]', tokens);
            setLoading(false);
            setMyTokens(tokens);
        }
        catch(err) {
            console.log('[err]', err);
        }
    }

    // useEffect(() => {
    //     if (walletAddr === "" || walletAddr === undefined || walletAddr === null) router.push('/');
    // }, [walletAddr]);

    useEffect(() => {
        if (walletAddr) getTokens();
    }, [walletAddr]);

    return (
        <React.Fragment>
            <Head>
                <title>My Collection - Fathom Yacht Club</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <main className="sm:pt-20">
                <section className="bg-background-light pt-16 sm:mt-1 pb-16">
                    <div className="container w-4/5">
                        <h1 className="text-primary text-center font-bold font-muli text-5xl sm:text-6xl py-6">My Collection</h1>
                    </div>
                </section>

                {
                    loading ? (
                        <React.Fragment>
                            <div className="container flex items-center justify-center p-28">
                                <span className="block animate-spin bg-transparent border-3 border-t-primary rounded-full h-10 w-10"></span>
                            </div>
                        </React.Fragment>
                    ) : (
                        <section>
                            <Collection tokens={myTokens} />
                        </section>
                    ) 
                }
            </main>
        </React.Fragment>
    );
};