import React from 'react';
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>FATHOM YACHT CLUB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-24">
        <section className="container pt-14 my-4 pb-28">
          <div className="flex items-center">
            <div className="w-1/2 pr-2 pl-2 sm:pl-0 sm:pr-12">
              <h1 className="text-blue-800 font-normal text-6xl py-4 mb-4">NFT Yacht Club</h1>
              <p className="text-gray-800 text-xl font-thin py-2 mb-8">Fathom Yacht Club is one of the first decentralized Yacht and Social Clubs where membership is purchased through an NFT “token.” The token holder will have access to various social and VIP experiences in digital and physical spaces.</p>

              <button className="uppercase bg-gradient bg-blue-600 text-white py-4 px-8 rounded-full font-semibold">Coming Soon</button>
            </div>
            <div className="w-1/2 pl-2">
              <Image src="/images/hero-banner.jpg" className="w-full h-full" width={1600} height={1067} />
            </div>
          </div>
        </section>

        <section className="w-full min-h-96 yacht-section-1 mt-8"></section>

        <section className="container py-28">
          <h2 className="text-blue-800 text-6xl py-8 mb-8 text-center">Exclusive Membership</h2>

          <p className="pb-4 text-xl">Unlike traditional yacht clubs and social organizations that rely heavily on the proximity of its members in relation to a physical location of the club, Fathom Yacht Club will be a global community of thousands of forward thinking, like minded, individuals that will have the opportunity to meet regularly through our digital and virtual platforms and also have physical access to various real world experiences such as social events, parties, flotillas, and access to use of real world boats and yachts 35’ to 75’ and larger.</p>

          <h3 className="text-3xl text-blue-800">Creating Value for Our Members</h3>
          <p className="pb-4 text-xl">Fathom Yacht Club NFT membership becomes an asset to the token holder that can be sold, transferred, or leased to others on the secondary market. By utilizing NFT’s, FYC can create a member-driven community to provide unique experiences for token holders. In addition, NFTs create an opportunity that allows FYC to deliver exceptional and dynamic offerings well into the future.  </p>

          <h3 className="text-3xl text-blue-800">FYC’s Commitment to Ocean Conservation</h3>
          <p className="pb-4 text-xl">FYC recognizes the importance of protecting the world’s oceans. Therefore, FYC has committed to donating 10% of all royalties that FYC receives annually to a charity dedicated to ocean conservation.</p>
        </section>

        <section className="w-full min-h-96 yacht-section-2 mt-8"></section>
      </main>
    </React.Fragment>
  );
};
