import React from 'react';
import Head from 'next/head';
import Newsletter from '../components/sections/Newsletter';
import Locations from '../components/sections/Locations';

export default function About() {
    return (
        <React.Fragment>
            <Head>
                <title>Locations - Fathom Yacht Club</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <main className="sm:pt-20">
                <section className="bg-background-light pt-16 sm:mt-1 pb-16">
                    <div className="container w-4/5">
                        <h1 className="text-primary text-center font-bold font-muli text-5xl sm:text-6xl py-6">Locations</h1>
                    </div>
                </section>

                <section>
                    <Locations />
                </section>
        
                <section>
                    <Newsletter />
                </section>
            </main>
        </React.Fragment>
    );
};