import React from 'react';
import Head from 'next/head';
import Newsletter from '../components/sections/Newsletter';
import Purchase from '../components/sections/Purchase';
import { useRouter } from 'next/router';

export default function Membership() {
    return (
        <React.Fragment>
            <Head>
                <title>Membership - Fathom Yacht Club</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <main className="sm:pt-20">
                <section className="bg-background-light pt-16 sm:mt-1 pb-16">
                    <div className="container w-4/5">
                        <h1 className="text-primary text-center font-bold font-muli text-5xl sm:text-6xl py-6">Become a member</h1>
                        <p className="font-normal text-xl leading-9 mb-6 text-center">You can purchase up to two tokens per transaction with no limit on the number of tokens you can purchase.</p>
                    </div>
                </section>

                <section className="py-16">
                    <Purchase />
                </section>
        
                <section>
                    <Newsletter />
                </section>
            </main>
        </React.Fragment>
    );
};