import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import TokenDetail from '../../components/sections/TokenDetail';
import { useSelector } from 'react-redux';
import Web3 from 'web3';
import axios from 'axios';
import Modal from '../../components/modals/Modal';

const { abi } = require("../../contracts/Leasing.json");
const leaseContractAddress = process.env.NEXT_PUBLIC_LEASE_CONTRACT_ADDRESS;
const tokenBatchURI = process.env.NEXT_PUBLIC_TOKEN_BATCH_URI;

export default function Location() {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [metaData, setMetaData] = useState();
    const [loading, setLoading] = useState(false);
    const walletAddr = useSelector((state) => state.address);
    const router = useRouter();
    const { id } = router.query

    const getMetaData = async () => {
        try {
            setLoading(true);

            const result = await axios.get(tokenBatchURI + '/' + id);
            console.log('[result]', result);
            setLoading(false);
            setMetaData(result.data);
        }
        catch(err) {
            console.log('[err]', err);
        }
    }

    const leaseHandler = async (tokenId) => {
        try {
            setIsModalOpen(true);
        }
        catch (err) {
            console.log('[err]', err);
        }
    }

    function closeModal() {
        setIsModalOpen(false);
    }

    function openModal() {
        setIsModalOpen(true);
    }
    

    useEffect(() => {
        if (id) getMetaData();
    }, [id]);

    return (
        <React.Fragment>
            <Head>
                <title>{ metaData ? metaData.name : `Token #${id}` } - Fathom Yacht Club</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <main className="sm:pt-20">
                {
                    loading ? (
                        <React.Fragment>
                            <div className="container flex items-center justify-center p-28">
                                <span className="block animate-spin bg-transparent border-3 border-t-primary rounded-full h-10 w-10"></span>
                            </div>
                        </React.Fragment>
                    ) : (
                        metaData && <section>
                            <TokenDetail metaData={metaData} leaseHandler={leaseHandler} />
                        </section>
                    ) 
                }

                <Modal isOpen={isModalOpen} openModal={openModal} closeModal={closeModal}>
                    Hey, modal!
                </Modal>
            </main>
        </React.Fragment>
    );
};